### ISSUE TITLE
Styling of "answer"

### ISSUE THREAD

**Issue by exetico** [angusmcleod/discourse-quick-messages#11] opened 2018-03-20 15:31 UTC
Hi'

We're seeing some problems with our branding-colors.
![image](https://user-images.githubusercontent.com/3549445/37664736-3127a09e-2c5c-11e8-95bf-fc33d313386e.png)

Are you able to fix this?

**Comment by fbjerggaard** [comment] 2018-04-23 14:55
Researching this a bit, I noticed the following:
1) Any "old" messages HTML looks like the following:
```
<div class="cooked">
    <p>This is a message</p>
</div>
```

While any newly sent messages looks like this:

```
<div class="cooked">
    Message
</div>
```

This can be fixed by either:
- Adding the `<p>` tag to newly sent messages
- Adjusting the stylesheet so the color doesn't only apply to stuff in the `<p>` tag

The first solution is obviously the best.

**Comment by angusmcleod** [comment] 2018-04-25 00:52
Sorry for the slow response here.

While we could just make a css tweak here, the issue is actually a bit deeper. 

When you compose a quick message the message is initially 'staged' while it is being sent to the server, i.e. it is optimistically added to the author's poststream before it is actually saved and sent to other users. This let's it appear instantly in the user's poststream (normal Discourse does the same thing). When staged, the 'cooked' version of the post is not wrapped in paragraph tags.

After the post is saved on the server, a properly cooked version of the post is returned to the client. This version is wrapped in paragraph tags. There is some utility in this difference, in that we can use it to show the user that this roundtrip is going on, in a way you often see in messenger clients, namely:

![2018-04-25 10 46 13](https://user-images.githubusercontent.com/5931623/39220790-b7588daa-4876-11e8-8fb8-2087ecfc4189.gif)

Please update and give this change a go.

https://github.com/angusmcleod/discourse-quick-messages/commit/2688cb6cdbdde7abfae6d91360b42f24d6170483

**Closed by angusmcleod** 2018-04-25 00:52 UTC
